// 새 영상을 추가할 때는 아래 LESSONS 배열에 같은 형식의 객체를 하나 더 넣으세요.
// start와 end는 초 단위입니다. 예: 1분 23.5초 → 83.5
window.LESSONS = [
  {
    id: "morning-routine",
    order: 1,
    title: "La mia routine mattutina",
    topic: "아침 일상 표현",
    level: "A0–A1",
    creator: "Elisa’s Italian School",
    videoTitle: "Slow Italian for Beginners – Morning Routine in Easy Italian",
    videoId: "40ao6UQlx1o",
    sourceUrl: "https://www.youtube.com/watch?v=40ao6UQlx1o",
    durationLabel: "약 3분",
    rangeLabel: "선택 구간 01:00–03:52",
    sentences: [
      { start: 59.8, end: 72.0, it: "La mattina mi alzo dal letto quando la sveglia inizia a suonare.", ko: "아침에는 알람이 울리기 시작하면 침대에서 일어나요." },
      { start: 71.8, end: 80.0, it: "Trin, trin, suona la sveglia, io mi alzo.", ko: "따르릉, 따르릉, 알람이 울리고 저는 일어나요." },
      { start: 79.8, end: 87.0, it: "La mia sveglia suona alle sette di mattina, circa.", ko: "제 알람은 대략 아침 7시에 울려요." },
      { start: 86.8, end: 92.0, it: "Precisamente suona alle sette e cinque.", ko: "정확히는 7시 5분에 울려요." },
      { start: 91.8, end: 96.0, it: "Trin, trin. Suona la sveglia.", ko: "따르릉, 따르릉. 알람이 울려요." },
      { start: 95.8, end: 101.0, it: "Mi alzo e inizio la mia giornata.", ko: "저는 일어나서 하루를 시작해요." },
      { start: 103.8, end: 115.0, it: "Per prima cosa, dopo essermi alzata, dopo che è suonata la sveglia, vado in bagno.", ko: "먼저, 일어나고 알람이 울린 뒤 화장실로 가요." },
      { start: 114.8, end: 127.0, it: "La porta del bagno è chiusa, quindi apro la porta ed entro in bagno.", ko: "화장실 문이 닫혀 있어서 문을 열고 안으로 들어가요." },
      { start: 126.8, end: 135.0, it: "Ma in bagno è buio.", ko: "그런데 화장실 안은 어두워요." },
      { start: 134.8, end: 138.0, it: "È buio, non c’è luce.", ko: "어두워요. 불빛이 없어요." },
      { start: 138.8, end: 144.0, it: "Quindi accendo la luce.", ko: "그래서 불을 켜요." },
      { start: 143.8, end: 147.0, it: "Ecco qui. Ho acceso la luce.", ko: "자, 됐어요. 불을 켰어요." },
      { start: 148.8, end: 152.0, it: "Mi lavo la faccia.", ko: "세수를 해요." },
      { start: 151.8, end: 157.0, it: "Apro il rubinetto. Ho aperto il rubinetto.", ko: "수도꼭지를 열어요. 수도꼭지를 열었어요." },
      { start: 156.8, end: 162.0, it: "E poi mi lavo la faccia.", ko: "그런 다음 세수를 해요." },
      { start: 161.8, end: 171.0, it: "Mi lavo la faccia con l’acqua fredda, di solito abbastanza fredda.", ko: "보통 꽤 차가운 물로 세수를 해요." },
      { start: 170.8, end: 173.0, it: "Ma ora la mia faccia è bagnata.", ko: "그런데 이제 제 얼굴이 젖었어요." },
      { start: 172.8, end: 178.0, it: "Quindi prendo un asciugamano.", ko: "그래서 수건을 하나 집어요." },
      { start: 177.8, end: 187.0, it: "Prendo un asciugamano e mi asciugo la faccia.", ko: "수건을 집어서 얼굴을 닦아요." },
      { start: 186.8, end: 190.0, it: "Ora la mia faccia è asciutta.", ko: "이제 얼굴이 말랐어요." },
      { start: 189.8, end: 198.0, it: "Poi prendo il mio spazzolino, lo spazzolino.", ko: "그다음 제 칫솔을 집어요. 칫솔이에요." },
      { start: 197.8, end: 202.0, it: "E mi lavo i denti.", ko: "그리고 이를 닦아요." },
      { start: 201.8, end: 213.0, it: "Mi lavo i denti, ovviamente non solo con lo spazzolino, ma anche con il dentifricio.", ko: "물론 칫솔만이 아니라 치약도 사용해서 이를 닦아요." },
      { start: 213.8, end: 227.0, it: "Metto il dentifricio sullo spazzolino e poi, con lo spazzolino, mi lavo i denti.", ko: "칫솔에 치약을 묻히고 칫솔로 이를 닦아요." },
      { start: 226.8, end: 232.0, it: "Ok, mi lavo i denti, poi spengo la luce.", ko: "좋아요, 이를 닦고 불을 꺼요." }
    ]
  },
  {
    id: "pizza-preferita",
    order: 2,
    title: "La mia pizza preferita",
    topic: "음식과 가족 이야기",
    level: "A1–A2",
    creator: "Epic Italian Journey",
    videoTitle: "LISTEN & LEARN ITALIAN – Short Story for Complete Beginners (A1-A2)",
    videoId: "ZeYNmb4qHps",
    sourceUrl: "https://www.youtube.com/watch?v=ZeYNmb4qHps",
    durationLabel: "약 2분",
    rangeLabel: "선택 구간 00:28–02:31",
    sentences: [
      { start: 28.0, end: 34.0, it: "Ciao, mi chiamo Luca e oggi voglio raccontarti della mia pizza preferita.", ko: "안녕하세요, 저는 루카이고 오늘 제가 가장 좋아하는 피자에 관해 이야기해 드릴게요." },
      { start: 34.0, end: 44.0, it: "Ogni venerdì sera, la mia famiglia ed io ordiniamo la pizza da una pizzeria vicino a casa nostra.", ko: "매주 금요일 저녁, 우리 가족과 저는 집 근처 피자 가게에서 피자를 주문해요." },
      { start: 44.0, end: 48.0, it: "La pizzeria si chiama Da Mario.", ko: "그 피자 가게의 이름은 ‘다 마리오’예요." },
      { start: 48.0, end: 55.0, it: "Mario, il pizzaiolo, fa le pizze più buone.", ko: "피자 요리사 마리오는 가장 맛있는 피자를 만들어요." },
      { start: 55.0, end: 60.0, it: "Io scelgo sempre la pizza margherita.", ko: "저는 항상 마르게리타 피자를 골라요." },
      { start: 60.0, end: 65.0, it: "La conosci? È una pizza semplice ma molto famosa.", ko: "알고 있나요? 단순하지만 아주 유명한 피자예요." },
      { start: 65.0, end: 73.0, it: "Gli ingredienti sono pomodoro, mozzarella e basilico.", ko: "재료는 토마토, 모차렐라 그리고 바질이에요." },
      { start: 73.0, end: 80.0, it: "Il basilico ha un buon profumo e la mozzarella si scioglie sul pomodoro.", ko: "바질은 향이 좋고 모차렐라는 토마토 위에서 녹아요." },
      { start: 80.0, end: 86.0, it: "Quando la mangio, mi sembra di essere in Italia.", ko: "그 피자를 먹으면 이탈리아에 있는 것처럼 느껴져요." },
      { start: 86.0, end: 91.0, it: "Mia sorella non ama la pizza margherita.", ko: "제 여동생은 마르게리타 피자를 좋아하지 않아요." },
      { start: 91.0, end: 97.0, it: "Lei preferisce la pizza quattro formaggi perché ama il formaggio.", ko: "여동생은 치즈를 좋아해서 콰트로 포르마지 피자를 더 좋아해요." },
      { start: 97.0, end: 103.0, it: "La sua pizza ha mozzarella, gorgonzola, parmigiano e provolone.", ko: "그 피자에는 모차렐라, 고르곤졸라, 파르미자노와 프로볼로네가 들어가요." },
      { start: 103.0, end: 107.0, it: "È molto saporita e cremosa.", ko: "아주 풍미가 좋고 부드러워요." },
      { start: 107.0, end: 116.0, it: "A volte mi dà un pezzetto, ma preferisco sempre la mia margherita.", ko: "가끔 제게 한 조각을 주지만, 저는 언제나 제 마르게리타를 더 좋아해요." },
      { start: 116.0, end: 120.0, it: "A mia mamma piace la pizza vegetariana.", ko: "엄마는 채소 피자를 좋아하세요." },
      { start: 120.0, end: 128.0, it: "Ha molte verdure come zucchine, melanzane, peperoni e pomodori.", ko: "거기에는 주키니, 가지, 피망, 토마토 같은 채소가 많이 들어가요." },
      { start: 128.0, end: 133.0, it: "Dice che è leggera e salutare.", ko: "엄마는 그 피자가 가볍고 건강에 좋다고 말하세요." },
      { start: 133.0, end: 139.0, it: "Dopo aver mangiato la pizza, parliamo e ridiamo.", ko: "피자를 먹은 뒤 우리는 이야기하고 웃어요." },
      { start: 139.0, end: 143.0, it: "A volte guardiamo un film o giochiamo a carte.", ko: "가끔 영화를 보거나 카드놀이를 해요." },
      { start: 143.0, end: 151.0, it: "È una serata speciale con la mia famiglia.", ko: "가족과 함께하는 특별한 저녁이에요." }
    ]
  },
  {
    id: "presentarsi-in-italiano",
    order: 3,
    title: "Presentarsi in italiano",
    topic: "자기소개와 일상 질문",
    level: "A0–A1",
    creator: "Easy Italian",
    videoTitle: "Introduce Yourself in Italian (for absolute beginners) | Super Easy Italian 48",
    videoId: "ieyLUxtwch4",
    sourceUrl: "https://www.youtube.com/watch?v=ieyLUxtwch4",
    durationLabel: "약 1분",
    rangeLabel: "선택 구간 00:35–04:31",
    sentences: [
      { start: 35.6, end: 37.9, it: "Come ti chiami?", ko: "이름이 뭐예요?" },
      { start: 40.6, end: 42.5, it: "Sono Elena, piacere.", ko: "저는 엘레나예요. 반가워요." },
      { start: 44.6, end: 46.3, it: "Mi chiamo Ludovica.", ko: "제 이름은 루도비카예요." },
      { start: 62.6, end: 64.7, it: "Dove abiti?", ko: "어디에 살아요?" },
      { start: 65.5, end: 67.3, it: "Abito a Milano.", ko: "밀라노에 살아요." },
      { start: 73.7, end: 77.4, it: "Di dove sei?", ko: "어디 출신이에요?" },
      { start: 77.5, end: 78.9, it: "Vengo da Venezia.", ko: "베네치아에서 왔어요." },
      { start: 79.9, end: 81.3, it: "Sono inglese.", ko: "저는 영국인이에요." },
      { start: 84.8, end: 85.9, it: "Sono di Roma.", ko: "저는 로마 출신이에요." },
      { start: 94.4, end: 99.9, it: "Io sono nativa di Trento, ma vivo a Milano da tantissimi anni.", ko: "저는 트렌토 태생이지만 아주 오랫동안 밀라노에서 살고 있어요." },
      { start: 206.3, end: 208.3, it: "Che lavoro fai?", ko: "무슨 일을 해요?" },
      { start: 211.7, end: 213.7, it: "Lavoro per una compagnia aerea.", ko: "항공사에서 일해요." },
      { start: 213.6, end: 215.7, it: "Faccio la studentessa.", ko: "저는 학생이에요." },
      { start: 215.6, end: 216.6, it: "Cosa studi?", ko: "무엇을 공부해요?" },
      { start: 216.5, end: 218.8, it: "Studio ingegneria informatica.", ko: "컴퓨터공학을 공부해요." },
      { start: 251.7, end: 254.6, it: "Cosa fai nel tempo libero?", ko: "여가 시간에는 무엇을 해요?" },
      { start: 254.5, end: 258.8, it: "Nel tempo libero pratico sport e mi riposo.", ko: "여가 시간에는 운동을 하고 쉬어요." },
      { start: 260.8, end: 262.9, it: "Mi piace guardare film.", ko: "영화 보는 것을 좋아해요." },
      { start: 264.1, end: 267.1, it: "Mi piace fare le passeggiate.", ko: "산책하는 것을 좋아해요." },
      { start: 267.0, end: 271.4, it: "Mi piace ascoltare la musica e andare in palestra.", ko: "음악을 듣고 헬스장에 가는 것을 좋아해요." }
    ]
  },
  {
    id: "colazione-al-bar",
    order: 4,
    title: "Colazione al bar",
    topic: "카페 주문과 선택 표현",
    level: "A1",
    creator: "Easy Italian",
    videoTitle: "How to Order Breakfast in Italy Like a Local | Easy Italian 261",
    videoId: "Q28_M_fBUT0",
    sourceUrl: "https://www.youtube.com/watch?v=Q28_M_fBUT0",
    durationLabel: "약 1분",
    rangeLabel: "선택 구간 00:52–15:39",
    sentences: [
      { start: 51.8, end: 54.4, it: "Ragazzi, voi vi accomodate?", ko: "여러분, 자리에 앉으실 건가요?" },
      { start: 54.2, end: 56.3, it: "Sì, magari fuori.", ko: "네, 가능하면 밖에요." },
      { start: 55.3, end: 61.2, it: "Allora, prendiamo un cappuccino, un caffè macchiato e un caffè normale.", ko: "그럼 카푸치노 하나, 마키아토 하나, 일반 커피 하나로 할게요." },
      { start: 62.4, end: 64.7, it: "Che brioche vuoi?", ko: "어떤 브리오슈를 원해?" },
      { start: 64.8, end: 68.5, it: "Prendiamo anche una brioche vuota per me.", ko: "저를 위해 속이 없는 브리오슈도 하나 주문할게요." },
      { start: 72.5, end: 74.8, it: "Ecco qua, grazie.", ko: "여기 있습니다. 감사합니다." },
      { start: 420.7, end: 427.5, it: "Buongiorno. Un caffè macchiato decaffeinato, per favore.", ko: "안녕하세요. 디카페인 마키아토 한 잔 부탁드려요." },
      { start: 428.5, end: 432.2, it: "Hai qualcosa di piccolino?", ko: "작은 것으로 뭐가 있나요?" },
      { start: 436.7, end: 439.0, it: "Tu vuoi qualcosa?", ko: "너도 뭐 먹을래?" },
      { start: 439.0, end: 444.4, it: "Una sfogliatella con la cioccolata o la crema. Cosa preferisci?", ko: "초콜릿이나 크림이 든 스폴리아텔라가 있어. 어떤 게 좋아?" },
      { start: 569.4, end: 573.7, it: "Ciao, scusa, posso chiederti com'è questo?", ko: "안녕하세요, 실례지만 이것이 어떤 건지 물어봐도 될까요?" },
      { start: 573.1, end: 579.0, it: "Volevamo una brioche salata con prosciutto cotto e brie.", ko: "익힌 햄과 브리 치즈가 든 짭짤한 브리오슈 하나 주세요." },
      { start: 585.0, end: 591.4, it: "Poi volevamo due spremute d'arancia.", ko: "그리고 생오렌지주스 두 잔 주세요." },
      { start: 591.4, end: 594.0, it: "E tu, Antonella, cosa prendi?", ko: "안토넬라, 너는 무엇을 주문할래?" },
      { start: 593.0, end: 596.4, it: "Un tè e un caffè decaffeinato.", ko: "차 한 잔과 디카페인 커피 한 잔이요." },
      { start: 730.3, end: 732.3, it: "Vuoi assaggiare un po'?", ko: "조금 맛볼래?" },
      { start: 731.9, end: 733.8, it: "No, grazie.", ko: "아니요, 괜찮아요." },
      { start: 783.5, end: 789.3, it: "Buongiorno, per favore, posso avere un cappuccino e una brioche?", ko: "안녕하세요. 카푸치노 한 잔과 브리오슈 하나 주시겠어요?" },
      { start: 847.5, end: 852.5, it: "Avete una bustina di zucchero di canna?", ko: "갈색 설탕 한 봉지가 있나요?" },
      { start: 933.5, end: 939.5, it: "Scusi, ma cosa c'è dentro questa brioche?", ko: "실례합니다. 이 브리오슈 안에는 무엇이 들어 있나요?" }
    ]
  }
];
